### ISSUE TITLE
Tracking issue for buildbot

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#58]
This one tracks an automated build platform to run tests and do merges automatically.
- [x] set up daily rustc container refresh
- [ ] set up zinc sources pull on update (also PRs)
- [ ] make zinc compilable in "native" mode (the host is armv7l, there's no armv7-m stdlib; should look more into compiler-rt?; also required by #50)
- [ ] submit artifacts on successful build
- [x] merge PR on successful tests run
